---
title: Educational Technology Project - Combined Data Analysis - EduTech (Fall 2015, Spring 2016 and Fall 2016), KBAI (Summer 2015 and Summer 2016) and HCI (Fall 2016) Data Analysis
output:
  pdf_document: default
  html_document: default
---

###Process Data###
```{r setup, echo=TRUE, results='hide', warning=FALSE}
# Set cwd
setwd("D:/Documents/Data Science/Educational Technology/R/Combined")
#setwd("E:/Educational Technology/R/Combined")
getwd()

# Load libraries
library(plyr)
library(tools)
library(ggplot2)

# Read in survey data sets
CS6460_fall15_soc = read.csv('Survey_CS6460_FALL15_SOC.csv')
CS6460_fall15_qc = read.csv('Survey_CS6460_FALL15_QC.csv')
CS6460_fall15_mc = read.csv('Survey_CS6460_FALL15_MC.csv')
CS6460_fall15_eoc = read.csv('Survey_CS6460_FALL15_EOC.csv')

CS6460_spr16_soc = read.csv('Survey_CS6460_SPR16_SOC.csv')
CS6460_spr16_qc = read.csv('Survey_CS6460_SPR16_QC.csv')
CS6460_spr16_mc = read.csv('Survey_CS6460_SPR16_MC.csv')
CS6460_spr16_eoc = read.csv('Survey_CS6460_SPR16_EOC.csv')

CS6460_fall16_soc = read.csv('Survey_CS6460_FALL16_SOC.csv')
CS6460_fall16_qc = read.csv('Survey_CS6460_FALL16_QC.csv')
CS6460_fall16_mc = read.csv('Survey_CS6460_FALL16_MC.csv')
CS6460_fall16_eoc = read.csv('Survey_CS6460_FALL16_EOC.csv')

CS7637_sum15_soc = read.csv('Survey_CS7637_SUM15_SOC.csv')
CS7637_sum15_qc = read.csv('Survey_CS7637_SUM15_QC.csv')
CS7637_sum15_mc = read.csv('Survey_CS7637_SUM15_MC.csv')
CS7637_sum15_eoc = read.csv('Survey_CS7637_SUM15_EOC.csv')

CS7637_sum16_soc = read.csv('Survey_CS7637_SUM16_SOC.csv')
CS7637_sum16_qc = read.csv('Survey_CS7637_SUM16_QC.csv')
CS7637_sum16_mc = read.csv('Survey_CS7637_SUM16_MC.csv')
CS7637_sum16_eoc = read.csv('Survey_CS7637_SUM16_EOC.csv')

CS6750_fall16_soc = read.csv('Survey_CS6750_FALL16_SOC.csv')
CS6750_fall16_qc = read.csv('Survey_CS6750_FALL16_QC.csv')
CS6750_fall16_mc = read.csv('Survey_CS6750_FALL16_MC.csv')
CS6750_fall16_eoc = read.csv('Survey_CS6750_FALL16_EOC.csv')
```

```{r process data, echo=TRUE, results = 'hide'}

# Create data subsets containing information of interest and change names
# CS6460 - EduTech
CS6460_fall15_soc = CS6460_fall15_soc[, c(1, 2, 3, 4, 5, 7, 8, 10)]
colnames(CS6460_fall15_soc) = c("student", "age", "gender", "birth", "residence", 
                                "language", "english", "education")

CS6460_spr16_soc = CS6460_spr16_soc[, c(1, 2, 3, 4, 5, 7, 8, 10)]
colnames(CS6460_spr16_soc) = c("student", "age", "gender", "birth", "residence", 
                               "language", "english", "education")

CS6460_fall16_soc = CS6460_fall16_soc[, c(1, 2, 3, 4, 5, 7, 8, 10)]
colnames(CS6460_fall16_soc) = c("student", "age", "gender", "birth", "residence", 
                                "language", "english", "education")


CS6460_fall15_qc = CS6460_fall15_qc[, c(1, 2, 3)]
colnames(CS6460_fall15_qc) = c("student", "conf_p1_post", "conf_p2_pre")

CS6460_spr16_qc = CS6460_spr16_qc[, c(1, 2, 3)]
colnames(CS6460_spr16_qc) = c("student", "conf_p1_post", "conf_p2_pre")

CS6460_fall16_qc = CS6460_fall16_qc[, c(1, 13, 14)]
colnames(CS6460_fall16_qc) = c("student", "conf_p1_post", "conf_p2_pre")


CS6460_fall15_mc = CS6460_fall15_mc[, c(1, 2, 3)]
colnames(CS6460_fall15_mc) = c("student", "conf_p2_post", "conf_p3_pre")

CS6460_spr16_mc = CS6460_spr16_mc[, c(1, 2, 3)]
colnames(CS6460_spr16_mc) = c("student", "conf_p2_post", "conf_p3_pre")

CS6460_fall16_mc = CS6460_fall16_mc[, c(1, 2, 3)]
colnames(CS6460_fall16_mc) = c("student", "conf_p2_post", "conf_p3_pre")


CS6460_fall15_eoc = CS6460_fall15_eoc[, c(1, 2, 11)]
colnames(CS6460_fall15_eoc) = c("student", "hours", "conf_p3_post")

CS6460_spr16_eoc = CS6460_spr16_eoc[, c(1, 2, 10)]
colnames(CS6460_spr16_eoc) = c("student", "hours", "conf_p3_post")

CS6460_fall16_eoc = CS6460_fall16_eoc[, c(1, 6, 14)]
colnames(CS6460_fall16_eoc) = c("student", "hours", "conf_p3_post")

# CS7637 - KBAI
CS7637_sum15_soc = CS7637_sum15_soc[, c(1, 2, 3, 4, 5, 7, 8, 16)]
colnames(CS7637_sum15_soc) = c("student", "age", "gender", "birth", "residence", 
                               "language", "english", "education")

CS7637_sum16_soc = CS7637_sum16_soc[, c(1, 2, 3, 4, 5, 7, 8, 11)]
colnames(CS7637_sum16_soc) = c("student", "age", "gender", "birth", "residence", 
                               "language", "english", "education")

CS7637_sum15_qc = CS7637_sum15_qc[, c(1, 4, 5)]
colnames(CS7637_sum15_qc) = c("student", "conf_p1_post", "conf_p2_pre")

CS7637_sum16_qc = CS7637_sum16_qc[, c(1, 3, 4)]
colnames(CS7637_sum16_qc) = c("student", "conf_p1_post", "conf_p2_pre")

CS7637_sum15_mc = CS7637_sum15_mc[, c(1, 4, 5)]
colnames(CS7637_sum15_mc) = c("student", "conf_p2_post", "conf_p3_pre")

CS7637_sum16_mc = CS7637_sum16_mc[, c(1, 3, 4)]
colnames(CS7637_sum16_mc) = c("student", "conf_p2_post", "conf_p3_pre")

CS7637_sum15_eoc = CS7637_sum15_eoc[, c(1, 3, 2)]
colnames(CS7637_sum15_eoc) = c("student", "hours", "conf_p3_post")

CS7637_sum16_eoc = CS7637_sum16_eoc[, c(1, 3, 2)]
colnames(CS7637_sum16_eoc) = c("student", "hours", "conf_p3_post")

# CS6750 - HCI
CS6750_fall16_soc = CS6750_fall16_soc[, c(1, 2, 3, 4, 5, 7, 8, 11)]
colnames(CS6750_fall16_soc) = c("student", "age", "gender", "birth", "residence", 
                                "language", "english", "education")

CS6750_fall16_qc = CS6750_fall16_qc[, c(1, 2, 3)]
colnames(CS6750_fall16_qc) = c("student", "conf_p1_post", "conf_p2_pre")

CS6750_fall16_mc = CS6750_fall16_mc[, c(1, 2, 3)]
colnames(CS6750_fall16_mc) = c("student", "conf_p2_post", "conf_p3_pre")

CS6750_fall16_eoc = CS6750_fall16_eoc[, c(1, 3, 2)]
colnames(CS6750_fall16_eoc) = c("student", "hours", "conf_p3_post")


# Merge EduTech datasets
edutech_data_fall15 = merge(x = CS6460_fall15_soc, y = CS6460_fall15_qc, 
                            by = "student", all.x = TRUE)
edutech_data_fall15 = merge(x = edutech_data_fall15, y = CS6460_fall15_mc, 
                            by = "student", all.x = TRUE)
edutech_data_fall15 = merge(x = edutech_data_fall15, y = CS6460_fall15_eoc, 
                            by = "student", all.x = TRUE)

edutech_data_spr16 = merge(x = CS6460_spr16_soc, y = CS6460_spr16_qc, 
                           by = "student", all.x = TRUE)
edutech_data_spr16 = merge(x = edutech_data_spr16, y = CS6460_spr16_mc, 
                           by = "student", all.x = TRUE)
edutech_data_spr16 = merge(x = edutech_data_spr16, y = CS6460_spr16_eoc, 
                           by = "student", all.x = TRUE)

edutech_data_fall16 = merge(x = CS6460_fall16_soc, y = CS6460_fall16_qc, 
                            by = "student", all.x = TRUE)
edutech_data_fall16 = merge(x = edutech_data_fall16, y = CS6460_fall16_mc, 
                            by = "student", all.x = TRUE)
edutech_data_fall16 = merge(x = edutech_data_fall16, y = CS6460_fall16_eoc, 
                            by = "student", all.x = TRUE)


edutech_data_fall15$semester = "Fall 2015"
edutech_data_spr16$semester = "Spring 2016"
edutech_data_fall16$semester = "Fall 2016"

edutech = rbind(edutech_data_fall15, edutech_data_spr16, edutech_data_fall16)

edutech$course = "EduTech"

# Drop unneeded datasets
rm(CS6460_fall15_soc, CS6460_fall15_qc, CS6460_fall15_mc, CS6460_fall15_eoc, 
   CS6460_spr16_soc, CS6460_spr16_qc, CS6460_spr16_mc, CS6460_spr16_eoc,
   CS6460_fall16_soc, CS6460_fall16_qc, CS6460_fall16_mc, CS6460_fall16_eoc,
   edutech_data_fall15, edutech_data_spr16, edutech_data_fall16)

# Merge KBAI datasets
kbai_data_sum15 = merge(x = CS7637_sum15_soc, y = CS7637_sum15_qc, 
                        by = "student", all.x = TRUE)
kbai_data_sum15 = merge(x = kbai_data_sum15, y = CS7637_sum15_mc, 
                        by = "student", all.x = TRUE)
kbai_data_sum15 = merge(x = kbai_data_sum15, y = CS7637_sum15_eoc, 
                        by = "student", all.x = TRUE)

kbai_data_sum16 = merge(x = CS7637_sum16_soc, y = CS7637_sum16_qc, 
                        by = "student", all.x = TRUE)
kbai_data_sum16 = merge(x = kbai_data_sum16, y = CS7637_sum16_mc, 
                        by = "student", all.x = TRUE)
kbai_data_sum16 = merge(x = kbai_data_sum16, y = CS7637_sum16_eoc, 
                        by = "student", all.x = TRUE)


kbai_data_sum15$semester = "Summer 2015"
kbai_data_sum16$semester = "Summer 2016"

kbai = rbind(kbai_data_sum15, kbai_data_sum16)

kbai$course = "KBAI"

# Drop unneeded datasets
rm(kbai_data_sum15, kbai_data_sum16, CS7637_sum15_eoc, CS7637_sum15_mc, CS7637_sum15_qc,
   CS7637_sum15_soc, CS7637_sum16_eoc, CS7637_sum16_mc, CS7637_sum16_qc, CS7637_sum16_soc)

# Merge HCI datasets
hci = merge(x = CS6750_fall16_soc, y = CS6750_fall16_qc, by = "student", all.x = TRUE)
hci = merge(x = hci, y = CS6750_fall16_mc, by = "student", all.x = TRUE)
hci = merge(x = hci, y = CS6750_fall16_eoc, by = "student", all.x = TRUE)

hci$semester = "Fall 2016"

hci$course = "HCI"

# Drop unneeded datasets
rm(CS6750_fall16_soc, CS6750_fall16_qc, CS6750_fall16_mc, CS6750_fall16_eoc)

# Stack data sets
combined = rbind(kbai, edutech, hci)

# Drop unneeded datasets
rm(kbai, edutech, hci)

# Replace blanks with NA
is.na(combined) = (combined=="")

# Convert factors into character strings
combined$student = as.character(combined$student)
combined$birth = as.character(combined$birth)
combined$residence = as.character(combined$residence)
combined$language = as.character(combined$language)

# Drop blank factor levels
combined$age = factor(combined$age)
combined$gender = factor(combined$gender)
combined$english = factor(combined$english)
combined$education = factor(combined$education)
combined$conf_p1_post = factor(combined$conf_p1_post)
combined$conf_p2_pre = factor(combined$conf_p2_pre)
combined$conf_p2_post = factor(combined$conf_p2_post)
combined$conf_p3_pre = factor(combined$conf_p3_pre)
combined$conf_p3_post = factor(combined$conf_p3_post)
combined$hours = factor(combined$hours)

# Simplify level names
combined$age = revalue(combined$age, c("No Answer" = NA))
combined$gender = revalue(combined$gender, c("No Answer" = NA))
combined$english = revalue(combined$english, c("Native speaker"="Native", 
                          "Fully fluent (non-native speaker)"="Fluent",
                          "Partially fluent" = "Partial", "No Answer" = NA))

combined$education = revalue(combined$education, c("Bachelors Degree"="Bachelors", 
    "Doctoral Degree"="Doctorate", "High School (or international equivalent)"="High School",
                        "Masters Degree" = "Masters", "No Answer" = NA))

combined$conf_p1_post = revalue(combined$conf_p1_post, c("Very confident" = 5, 
                    "Somewhat confident" = 4, "Neither confident nor unconfident" = 3,
                    "Somewhat unconfident" = 2, "Very unconfident" = 1))

combined$conf_p2_pre = revalue(combined$conf_p2_pre, c("Very confident" = 5, 
                    "Somewhat confident" = 4, "Neither confident nor unconfident" = 3,
                    "Somewhat unconfident" = 2, "Very unconfident" = 1))

combined$conf_p2_post = revalue(combined$conf_p2_post, c("Very confident" = 5, 
                    "Somewhat confident" = 4, "Neither confident nor unconfident" = 3,
                    "Somewhat unconfident" = 2, "Very unconfident" = 1))

combined$conf_p3_pre = revalue(combined$conf_p3_pre, c("Very confident" = 5, 
                    "Somewhat confident" = 4, "Neither confident nor unconfident" = 3,
                    "Somewhat unconfident" = 2, "Very unconfident" = 1))

combined$conf_p3_post = revalue(combined$conf_p3_post, c("Very confident" = 5, 
                    "Somewhat confident" = 4, "Neither confident nor unconfident" = 3,
                    "Somewhat unconfident" = 2, "Very unconfident" = 1))

combined$hours = revalue(combined$hours, c("No Answer" = NA))

combined$hours = revalue(combined$hours, c("<3 hours per week" = "0-3", 
                "3 - 6 hours per week" = "3-6", "6 - 9 hours per week" = "6-9", 
                "9 - 12 hours per week" = "9-12", "12 - 15 hours per week" = "12-15", 
                "15 - 18 hours per week" = "15-18", "18 - 21 hours per week" = "18-21", 
                "21 or more hours per week" = "21+"))

combined$hours = factor(combined$hours, levels = c("0-3", "3-6", "6-9", "9-12", "12-15",
                          "15-18", "18-21", "21+"))

combined$age = factor(combined$age, levels = c("Under 18", "18 to 24", "25 to 34", 
                                               "35 to 44", "45 to 54", "55 to 64"))

combined$course = factor(combined$course, levels = c("KBAI", "HCI", "EduTech"))
combined$semester = factor(combined$semester, levels = c("Fall 2016", "Summer 2016", 
                                              "Spring 2016", "Fall 2015", "Summer 2015"))

# Create function for removing "1:" from text fields and convert to title case
text_split = function(x){
  x = unlist(strsplit(x, ": "))[2]
  return(toTitleCase(x))
}

# Remove "1:" from text fields
combined$birth = sapply(combined$birth, text_split)
combined$residence = sapply(combined$residence, text_split)
combined$language = sapply(combined$language, text_split)

# Get lists of unique values
#unique(combined$birth)
#unique(combined$residence)
#unique(combined$language)

# Clean birth country names
combined$birth = ifelse(combined$birth %in% c("United States", "USA", "U.S.A.", "US", "Usa",
                    "Us", "The United States of America", "uSA", "United States of America",
                    "U.S.", "U.S", "Denver City, Tx", "Ethiopia - US Army Base"), "USA",
                    combined$birth)

combined$birth = ifelse(combined$birth %in% c("India", "INDIA"), "India", combined$birth)
combined$birth = ifelse(combined$birth %in% c("China", "People's Republic of China",
                    "P.R.CHINA", "Hong Kong, SAR", "Hong Kong", "CHINA", "China P.R."),
                    "China", combined$birth)
combined$birth = ifelse(combined$birth %in% c("South Korea", "Korea"), "Korea",
                        combined$birth)
combined$birth = ifelse(combined$birth %in% c("Addis Ababa", "Ethiopia"), "Ethiopia",
                       combined$birth)
combined$birth = ifelse(combined$birth %in% c("United Kingdom", "England"), "UK",
                       combined$birth)
combined$birth = ifelse(combined$birth == "NA", NA, combined$birth)

# Create alternative birth groupings
combined$birth2 = combined$birth
combined$birth2 = ifelse(combined$birth %in% c("Syria", "Taiwan", "Vietnam",
    "Pakistan", "Japan", "Korea", "Kuwait", "Philippines", "Indonesia", 
    "Sri Lanka", "Singapore", "Nepal", "Turkey", "Kazakhstan", "Iran",
    "Afghanistan", "Thailand", "Myanmar", "Lebanon", "Tunisia", "UAE",
    "Bangladesh", "Qatar", "Malaysia"), "Other Asia", combined$birth2)
combined$birth2 = ifelse(combined$birth %in% c("Ukraine", "Italy", "Norway",
    "Serbia", "Moldova", "Czech Republic", "Poland", "Russia", "Switzerland",
    "Germany", "Bulgaria", "UK", "Finland", "Romania", "Lithuania",
    "Luxembourg"), "Europe", combined$birth2)
combined$birth2 = ifelse(combined$birth %in% c("Puerto Rico", "Canada",
    "Dominican Republic", "Mexico", "Dominica", "El Salvador", "Cuba", 
    "Haiti", "Bahamas", "Guatemala", "Panama", "Grenada", "Honduras",
    "Nicaragua", "The Bahamas", "Trinidad and Tobago"), "Other Nth America",
    combined$birth2)
combined$birth2 = ifelse(combined$birth %in% c("Peru", "Ecuador", "Colombia",
    "Brazil", "Argentina", "Chile"), "Sth America", combined$birth2)
combined$birth2 = ifelse(combined$birth %in% c("Nigeria", "Kenya", 
    "South Africa", "Ethiopia", "Ghana", "Rwanda"), "Africa", combined$birth2)

combined$birth2 = ifelse(combined$birth %in% c("Australia", "New Zealand"),
    "Other", combined$birth2)

unique(combined$birth2)

# Clean residence country names
combined$residence = ifelse(combined$residence %in% c("United States", "USA", "U.S.A.", 
                    "US", "Usa",
                    "The United States of America", "uSA", "United States of America",
                    "United State", "USa", "Los Angeles", "Houston", "U.S", "U.S.", "YSA",
                    "Us", "United STates", "America", "JS"), "USA", combined$residence)

combined$residence = ifelse(combined$residence == "NA", NA, combined$residence)
combined$residence = ifelse(combined$residence == "Myanmar, Hong Kong", "Myanmar",
                            combined$residence)
combined$residence = ifelse(combined$residence %in% c("China", "Hong Kong"), "China",
                            combined$residence)
combined$residence = ifelse(combined$residence == "United Kingdom", "UK", combined$residence)

# Clean language
combined$language = ifelse(combined$language %in% c("English", "American English", "ENGLISH",
                  "American", "English (US)", "English Language", "Englist", 
                  "C++, but you Probably Mean \"English\"", "ENGLISH", "En", "JavaScript",
                  "Elijah", "Dallas", "First", 
                  "English and French", "English, Cantonese", "Java",
                  "Conative American Sign Language and English"), "English",
                  combined$language)
combined$language = ifelse(combined$language %in% c("Chinese", "Mandarin", "China", 
                  "Mandarin Chinese", "Cantonese", "Chiinese", "CHINESE", "Manderin", 
                  "Java", "Python"), "Chinese", combined$language)
combined$language = ifelse(combined$language %in% c("Marathi", "Telugu", "Bengali",
                  "Gujarati",
                  "Kannada", "Hindi", "Tamil", "Odiya", "TAMIL", "Punjabi", "Hindo", 
                  "Indian Language"), "Indian", combined$language)
combined$language = ifelse(combined$language %in% c("Principal", "Korean", "South Korean"), 
                  "Korean", combined$language)
combined$language = ifelse(combined$language == "Farsi/English", "Farsi", combined$language)
combined$language = ifelse(combined$language == "Spanish/English", "Spanish",
                           combined$language)
combined$language = ifelse(combined$language %in% c("Swiss German", "German", "Germany"), 
                  "German", combined$language)
combined$language = ifelse(combined$language %in% c("Persian", "Persian (Farsi)"), "Farsi",
                  combined$language)
combined$language = ifelse(combined$language %in% c("Thai", "ABAP"), "Thai",
                  combined$language)
combined$language = ifelse(combined$language == "NA", NA, combined$language)


# Create factors
combined$birth = factor(combined$birth)
combined$birth2 = factor(combined$birth2)
combined$residence = factor(combined$residence)
combined$language = factor(combined$language)
combined$semester = factor(combined$semester)

# Convert confidence scores to numeric
combined$conf_p1_post = as.numeric(as.character(combined$conf_p1_post))
combined$conf_p2_pre = as.numeric(as.character(combined$conf_p2_pre))
combined$conf_p2_post = as.numeric(as.character(combined$conf_p2_post))
combined$conf_p3_pre = as.numeric(as.character(combined$conf_p3_pre))
combined$conf_p3_post = as.numeric(as.character(combined$conf_p3_post))

# Calculate average confidence scores
combined$conf_ave = (combined$conf_p1_post + combined$conf_p2_pre + combined$conf_p2_post + 
                   combined$conf_p3_pre + combined$conf_p3_post)/5

combined$conf_pre_ave = (combined$conf_p2_pre + combined$conf_p3_pre)/2

combined$conf_post_ave = (combined$conf_p1_post + combined$conf_p2_post +
                            combined$conf_p3_post)/3

# Convert ranges to numeric values
combined$age_num = revalue(combined$age, c("18 to 24"=21, "25 to 34"=29.5, "35 to 44"=39.5, 
                                       "45 to 54"=49.5, "55 to 64"=59.5, "Under 18" = 18))
combined$age_num = as.numeric(as.character(combined$age_num))

combined$hours_num = revalue(combined$hours, c("0-3"=1.5, "3-6"=4.5, "6-9"=7.5, "9-12"=10.5, 
                  "12-15"=13.5, "15-18"=16.5, "18-21"=19.5, "21+"=21))
combined$hours_num = as.numeric(as.character(combined$hours_num))

# Create indicator variables
combined$native_ind = ifelse(combined$english == "Native", 1, 0)
combined$higher_ind = ifelse(combined$education %in% c("Masters", "Doctorate"), 1, 0)
combined$gender_ind = ifelse(combined$gender == "Male", 1, 0)

# Drop NA values
combined = subset(combined, !is.na(student))

```

###Explore Data###
```{r Calculate summary statistics}

# Calculate proportion & frequency of data set by course
prop.table(table(combined$course))
count(combined$course)

# Calculate counts by course and semester
data.frame(table(combined[,c("semester", "course")]))

# Calculate counts by course and semester and gender
data.frame(table(combined[,c("semester", "course", "gender")]))

# Determine number of duplicates
student_cnt = count(combined, "student")
student_cnt = student_cnt[order(-student_cnt$freq),]
multiple = subset(student_cnt, freq > 1)

dim(multiple)[1]
min(multiple$freq)
max(multiple$freq)

dim(subset(multiple, freq == 2))[1]
dim(subset(multiple, freq == 3))[1]

# For duplicates, keep the most recent occurrence of student in data set and drop 
#earlier values
combined = with(combined, combined[order(course, semester),])

combined = combined[!duplicated(combined$student),]

# Calculate summary statistics
summary(combined)

# Calculate proportion of class by gender
prop.table(table(combined$gender))

# Calculate proportion & frequency of data set by course
prop.table(table(combined$course))
count(combined$course)

# Calculate proportion of data set by semester
prop.table(table(combined$semester))

```

###Analyze Data by Gender###
```{r Calculate summary statistics by gender}

# Calculate age summary statistics
ddply(subset(combined, !is.na(age_num) & !is.na(gender)), "gender", summarise, 
      mean = mean(age_num), 
      sd = sd(age_num), median = median(age_num), first_q = quantile(age_num, 0.25),
      third_q = quantile(age_num, 0.75))

# Calculate study hours summary statistics
ddply(subset(combined, !is.na(gender)&!is.na(hours_num)), "gender", summarise, 
             mean = mean(hours_num), sd = sd(hours_num), median = median(hours_num), 
             first_q = quantile(hours_num, 0.25), third_q = quantile(hours_num, 0.75))

# Calculate confidence summary statistics
ddply(subset(combined, !is.na(gender)&!is.na(conf_ave)), "gender", summarise, 
             mean = mean(conf_ave), sd = sd(conf_ave), median = median(conf_ave), 
             first_q = quantile(conf_ave, 0.25), third_q = quantile(conf_ave, 0.75))

# Calculate confidence summary statistics
ddply(subset(combined, !is.na(gender)&!is.na(conf_pre_ave)), "gender", summarise, 
             mean = mean(conf_pre_ave), sd = sd(conf_pre_ave), median = median(conf_pre_ave),
             first_q = quantile(conf_pre_ave, 0.25), third_q = quantile(conf_pre_ave, 0.75))

ddply(subset(combined, !is.na(gender)&!is.na(conf_post_ave)), "gender", summarise, 
             mean = mean(conf_post_ave), sd = sd(conf_post_ave), 
             median = median(conf_post_ave), first_q = quantile(conf_post_ave, 0.25), 
             third_q = quantile(conf_post_ave, 0.75))

```


```{r Compare proportion of the class in each category by gender}

combined_m = subset(combined, gender == "Male")
combined_f = subset(combined, gender == "Female")

# Compare age
prop.table(table(combined_m$age))
prop.table(table(combined_f$age))

# Compare birth country
prop.table(table(combined_m$birth))
prop.table(table(combined_f$birth))

# Compare birth country2
prop.table(table(combined_m$birth2))
prop.table(table(combined_f$birth2))

# Compare country of residence
prop.table(table(combined_m$residence))
prop.table(table(combined_f$residence))

# Compare language background
prop.table(table(combined_m$language))
prop.table(table(combined_f$language))

# Compare English skills
prop.table(table(combined_m$english))
prop.table(table(combined_f$english))

# Compare education
prop.table(table(combined_m$education))
prop.table(table(combined_f$education))

# Compare hours
prop.table(table(combined_m$hours))
prop.table(table(combined_f$hours))

```


```{r Create graphs comparing distributions by gender}

#Boxplot of age distribution by gender
ggplot(subset(combined, !is.na(gender)), aes(gender, age_num)) + 
 geom_boxplot() + 
 labs(title = "Age Distribution by Gender",
      x = "Gender", y = "Age") +
 theme(plot.title = element_text(lineheight=.8, face="bold", hjust=0.5))

# Boxplot of hours spent studying by gender
ggplot(subset(combined, !is.na(hours_num) & !is.na(gender)), aes(gender, hours_num)) + 
  geom_boxplot() + 
 labs(title = "Study Hours Distribution by Gender",
      x = "Gender", y = "Study Hours") +
 theme(plot.title = element_text(lineheight=.8, face="bold", hjust=0.5))

# Boxplot of confidence score by gender
ggplot(subset(combined, !is.na(conf_ave) & !is.na(gender)), aes(gender, conf_ave)) + 
  geom_boxplot() + 
 labs(title = "Confidence Score Distribution by Gender",
      x = "Gender", y = "Average Confidence Score") +
 theme(plot.title = element_text(lineheight=.8, face="bold", hjust=0.5))

# Boxplot of confidence score (pre-project) by gender
ggplot(subset(combined, !is.na(conf_pre_ave) & !is.na(gender)), aes(gender,
    conf_pre_ave)) +  geom_boxplot() + 
 labs(title = "Confidence Score (Pre-Project) Distribution by Gender",
      x = "Gender", y = "Average Pre-Project Confidence Score") +
 theme(plot.title = element_text(lineheight=.8, face="bold", hjust=0.5))

# Boxplot of confidence score (post-project) by gender
ggplot(subset(combined, !is.na(conf_post_ave) & !is.na(gender)), aes(gender,
    conf_post_ave)) +  geom_boxplot() + 
 labs(title = "Confidence Score (Post-Project) Distribution by Gender",
      x = "Gender", y = "Average Post-Project Confidence Score") +
 theme(plot.title = element_text(lineheight=.8, face="bold", hjust=0.5))

# Bar chart comparing age by gender
ggplot(subset(combined, !is.na(gender)), aes(x = age)) + 
    geom_bar(fill = "blue") + 
    facet_wrap(~gender, scales = "free_y") +
    labs(title = "Age Distribution by Gender",
      x = "Age Band", 
      y = "Observations") +
    theme(plot.title = element_text(lineheight=.8, face="bold", hjust=0.5))

# Bar chart comparing English skills by gender
ggplot(subset(combined, !is.na(gender)), aes(x = english)) + 
    geom_bar(fill = "blue") + 
    facet_wrap(~gender, scales = "free_y") +
    labs(title = "English Skills by Gender",
      x = "English Skills", 
      y = "Observations") +
    theme(plot.title = element_text(lineheight=.8, face="bold", hjust=0.5))

# Bar chart comparing education by gender
ggplot(subset(combined, !is.na(gender)), aes(x = education)) + 
    geom_bar(fill = "blue") + 
    facet_wrap(~gender, scales = "free_y") +
    labs(title = "Highest Education Level by Gender",
      x = "Highest Level of Educational Attainment", 
      y = "Observations") +
    theme(plot.title = element_text(lineheight=.8, face="bold", hjust=0.5))

# Histogram of conf_ave by gender
ggplot(subset(combined, !is.na(gender)), aes(x = conf_ave)) + 
    geom_histogram(fill = "blue", binwidth = 0.5) + 
    facet_wrap(~gender, scale = "free_y") +
    labs(title = "Confidence Score Distribution by Gender",
      x = "Average Confidence Score", 
      y = "Observations") +
    theme(plot.title = element_text(lineheight=.8, face="bold", hjust=0.5))

# Histogram of conf_pre_ave by gender
ggplot(subset(combined, !is.na(gender)), aes(x = conf_pre_ave)) + 
    geom_histogram(fill = "blue", binwidth = 0.5) + 
    facet_wrap(~gender, scale = "free_y") +
    labs(title = "Pre-Project Confidence Score Distribution by Gender",
      x = "Average Pre-Project Confidence Score", 
      y = "Observations") +
    theme(plot.title = element_text(lineheight=.8, face="bold", hjust=0.5))

# Histogram of conf_post_ave by gender
ggplot(subset(combined, !is.na(gender)), aes(x = conf_post_ave)) + 
    geom_histogram(fill = "blue", binwidth = 0.5) + 
    facet_wrap(~gender, scale = "free_y") +
    labs(title = "Post-Project Confidence Score Distribution by Gender",
      x = "Average Post-Project Confidence Score", 
      y = "Observations") +
    theme(plot.title = element_text(lineheight=.8, face="bold", hjust=0.5))

# Histogram of study hours by gender
ggplot(subset(combined, !is.na(gender)), aes(x = hours_num)) + 
    geom_histogram(fill = "blue", binwidth = 1) + 
    facet_wrap(~gender, scale = "free_y") +
    labs(title = "Study Hours Distribution by Gender",
      x = "Average Hours Spent Studying per Week", 
      y = "Observations") +
    theme(plot.title = element_text(lineheight=.8, face="bold", hjust=0.5))

```

```{r Hypothesis tests to compare grades and mean age by gender}

# Age tests
t.test(combined_m$age_num, combined_f$age_num)
wilcox.test(age_num ~ gender, data=combined) 

# Higher ed tests
t.test(combined_m$higher_ind, combined_f$higher_ind)
wilcox.test(higher_ind ~ gender, data=combined) 

# Native speaker test
t.test(combined_m$native_ind, combined_f$native_ind)
wilcox.test(native_ind ~ gender, data=combined) 

# Average confidence score tests
t.test(combined_m$conf_ave, combined_f$conf_ave)
wilcox.test(conf_ave ~ gender, data=combined) 

# Average pre-project confidence score tests
t.test(combined_m$conf_pre_ave, combined_f$conf_pre_ave)
wilcox.test(conf_pre_ave ~ gender, data=combined) 

# Average post-project confidence score tests
t.test(combined_m$conf_post_ave, combined_f$conf_post_ave)
wilcox.test(conf_post_ave ~ gender, data=combined) 

# Study hours
t.test(combined_m$hours_num, combined_f$hours_num)
wilcox.test(hours_num ~ gender, data=combined)

```


```{r Fit regression models}

# Check for multicollinearity
cor_subset = combined[, c("age_num", "native_ind", "higher_ind", "gender_ind")]
cor(na.omit(cor_subset))

# Fit regression to confidence score
conf_lm = lm(conf_ave~gender + age_num + native_ind + higher_ind + semester + course,
             data=na.omit(combined))

summary(conf_lm)

# Fit regression to pre-project confidence score
conf_pre_lm = lm(conf_pre_ave~gender + age_num + native_ind + higher_ind + semester + course,
             data=na.omit(combined))

summary(conf_pre_lm)

# Fit regression to post-project confidence score
conf_post_lm = lm(conf_post_ave~gender + age_num + native_ind + higher_ind + 
                    semester + course, data=na.omit(combined))

summary(conf_post_lm)

# Fit regression to study hours
hours_lm = lm(hours_num~gender + age_num + native_ind + higher_ind + semester + course,
             data=na.omit(combined))

summary(hours_lm)

```

